server.port: 9999

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    reactor.netty.http.client: DEBUG

spring:
  application:
    name: gateway-ecommerce
  config:
    import:
      - aws-secretsmanager:/secret/algashop/gateway-ecommerce/redis-password?prefix=gateway-ecommerce.secrets.
      - aws-parameterstore:/config/algashop/gateway-ecommerce?prefix=gateway-ecommerce.params
      - aws-parameterstore:/config/algashop/shared?prefix=shared.params
  cloud:
    aws:
      credentials:
        access-key: test
        secret-key: test
      region:
        static: us-east-1
      endpoint: http://algashop-localstack:4566
    gateway:
      server:
        webflux:
          route-refresh-listener:
            enabled: false
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY, INTERNAL_SERVER_ERROR
                methods: GET,PUT
                exceptions: java.io.IOException, java.util.concurrent.TimeoutException
                backoff:
                  firstBackoff: 10ms
                  maxBackoff: 20ms
          httpclient:
            connect-timeout: ${gateway-ecommerce.params.httpclient.connect-timeout}
            response-timeout: ${gateway-ecommerce.params.httpclient.response-timeout}
          routes:
            - id: billing-route
              uri: lb://billing
              predicates:
                - Path=/api/v1/customers/me/credit-cards,/api/v1/customers/me/credit-cards/{creditCardId}
                - Method=GET,POST,PUT,DELETE,OPTIONS
            - id: ordering-route
              uri: lb://ordering
              predicates:
                - Path=/api/v1/customers/**,/api/v1/shipping-cost-previews,/api/v2/customers/**
                - Method=GET,POST,PUT,DELETE,OPTIONS
              filters:
                - name: CircuitBreaker
                  args:
                    name: ordering-route-cb
                    statusCodes:
                      - 502
                      - 504
                      - 500
            - id: product-catalog-route
              uri: lb://product-catalog
              predicates:
                - Path=/api/v1/products/**,/api/v1/categories/**
                - Method=GET,POST,PUT,DELETE,OPTIONS
              filters:
                - LocalResponseCache=1m,30MB
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter:
                      replenishRate: 50
                      burstCapacity: 200
                      requestedTokens: 1
                    key-resolver: "#{@rateLimitKeyResolver}"
            - id: user-management-route
              uri: lb://authorization-server
              predicates:
                - Path=/api/v1/users/**
                - Method=GET,POST,PUT,DELETE,OPTIONS
  data:
    redis:
      host: ${gateway-ecommerce.params.redis.host}
      port: ${gateway-ecommerce.params.redis.port}
      password: ${gateway-ecommerce.secrets.redis-password}
      database: ${gateway-ecommerce.params.redis.database}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${shared.params.auth-server-url}
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${shared.params.service-registry-url}/eureka
  instance:
    instanceId: ${random.uuid}
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health, gateway, circuitbreakers
  endpoint:
    gateway:
      enabled: true

resilience4j:
  timelimiter:
    configs:
      default:
        timeoutDuration: 60s
  circuitbreaker:
    instances:
      ordering-route-cb:
        slidingWindowSize: 8
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 5
        slidingWindowType: COUNT_BASED
        waitDurationInOpenState: 10s
        maxWaitDurationInHalfOpenState: 30s
        registerHealthIndicator: true